version: '3.9'
services:
  web:
    build: ./Frontend/frontend/
    ports:
      - "3000:80"
  backend:
    build: ./Backend
    ports:
      - "8081:8081"
  pythonsolver:
    build: ./Backend/pythonSolver