apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-point
  labels:
    name: ingress-point
spec:
  rules:
  - host: example.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ingress
            port: 
              number: 80
