{{- range $index, $deployment := .Values.Deployments }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .deployment.Name}}
spec:
  selector:
    matchLabels:
      app: {{ .deployment.matchLabels}}
  replicas: {{ .deployment.Replicas}}
  template:
    metadata:
      labels:
        app: {{ .deployment.matchLabels}}
    spec:
      containers:
        - name: {{ .deployment.Name}}
          image: {{.deployment.image}}
          imagePullPolicy: {{.deployment.imagePullPolicy}}
          ports:
            - name: http
              containerPort: {{.deployment.port}}
{{- end }}