apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: pappybuck/backend-local
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080