apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-solver
spec:
  selector:
    matchLabels:
      app: python-solver
  replicas: 2
  template:
    metadata:
      labels:
        app: python-solver
    spec:
      containers:
      - name: python-solver
        image: pappybuck/pythonsolver-local
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
